select maker, type from product where type = 'Laptop' order by maker;
select model, ram, screen, price from laptop where price > 1000 order by ram desc,price desc;
select * from printer where color = 'y' order by price;
select model, speed, hd, cd, price from pc where (cd = '12x' or '24x') and price < 600 order by speed desc;
select name, class from ships order by name;
select * from pc where speed >= 500 and price < 800 order by price desc;
select * from printer where type != 'Matrix' and price < 300 order by type desc;
select model, speed from pc where price between 400 and 600 order by hd;
select pc.model, pc.speed, pc.hd from pc left join product on pc.model=product.model where (pc.hd = 10 or pc.hd = 20) and product.maker = 'A' order by pc.speed;
select model, speed, hd, price from laptop where screen >= 12 order by price desc;
select model, type, price from printer where price < 300 order by type desc;
select model, ram, price from laptop where ram = 64 order by screen;
select model, ram, price from pc where ram > 64 order by hd;
select model, speed, price from pc where speed between 500 and 750 order by hd desc;
select * from outcome_o where outcome_o.out > 2000 order by date desc;
select * from income_o where inc between 5000 and 10000 order by inc;
select * from income where point = 1 order by inc;
select * from outcome where point = 2 order by outcome.out;
select * from classes where country = 'Japan' order by type desc;
select name, launched from ships where launched between 1920 and 1942 order by launched desc;
select ship, battle, result from outcomes where battle = 'Guadalcanal' and (result = 'OK' or result = 'damaged') order by ship desc;
select ship, battle, result from outcomes where result = 'sunk' order by ship desc;
select class, displacement from classes where displacement >= 40000 order by type;
select trip_no, town_from, town_to from trip where town_from = 'London' or town_to = 'London' order by time_out;
select trip_no, plane, town_from, town_to from trip where plane = 'TU-134' order by time_out desc;
select trip_no, plane, town_from, town_to from trip where plane != 'IL-86' order by plane;
select trip_no, town_from, town_to from trip where town_from != 'Rostov' and town_to != 'Rostov' order by plane;